version: '3.8'

services:
  semih-blog:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: semih-blog-live
    restart: unless-stopped
    networks:
      - internal_nw # Connect to your main Caddy reverse proxy network
    labels:
      # Optional: if you use Watchtower to auto-update
      # - "com.centurylinklabs.watchtower.enable=true"

networks:
  internal_nw:
    external: true