name: Deploy ToBranch

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.155.3"
          extended: true

      - name: Build
        run: hugo --minify
        
      - name: Push
        uses: nicholasgriffintn/github-branch-deployment-action@0.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: release-static-site
          FOLDER: ./public
          MESSAGE: 'Build: ({sha}) {msg}'